# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('chasis', models.CharField(choices=[('510', 'IPC-510'), ('610', 'IPC-610'), ('A4000', 'ACP-4000'), ('A4320', 'ACP-4320'), ('A2010', 'ACP-2010'), ('A4340', 'ACP-4340'), ('A4360', 'ACP-4360')], max_length=50)),
                ('chasis_serial', models.CharField(max_length=50)),
                ('motherboard', models.CharField(choices=[('I701', 'AIMB-701'), ('I767', 'AIMB-767'), ('I769', 'AIMB-769'), ('I780', 'AIMB-780'), ('I781', 'AIMB-781'), ('I782', 'AIMB-782'), ('I785', 'AIMB-785'), ('I784', 'AIMB-784'), ('S584', 'ASMB-584'), ('S784', 'ASMB-784'), ('S785', 'ASMB-785'), ('S781', 'ASMB-781'), ('S782', 'ASMB-782')], max_length=50)),
                ('board_serial', models.CharField(max_length=50)),
                ('configuration', models.TextField(blank=True)),
                ('others', models.TextField(blank=True)),
                ('entered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('entered',),
            },
        ),
    ]
